### ISSUE TITLE
Adapter crashes on startup: "uncaught exception: path.actions.getInfo is not a function"

### ISSUE THREAD

**Issue by buanet** [soef/ioBroker.tr-064#12]
Hi,
since I updated the adapter to 0.1.16 it crashes on startup and going on in some kind of bootloop.
Log says the following:

tr-064.0	2017-01-04 12:20:16.386	info	terminating
tr-064.0	2017-01-04 12:20:16.379	error	at Timer.listOnTimeout (timers.js:92:15)
tr-064.0	2017-01-04 12:20:16.379	error	at doIt [as _onTimeout] (/volume1/iobroker/node_modules/iobroker.tr-064/tr-064.js:491:32)
tr-064.0	2017-01-04 12:20:16.379	error	at TR064.getWLAN (/volume1/iobroker/node_modules/iobroker.tr-064/tr-064.js:351:5)
tr-064.0	2017-01-04 12:20:16.379	error	at callGetInfo (/volume1/iobroker/node_modules/iobroker.tr-064/tr-064.js:342:29)
tr-064.0	2017-01-04 12:20:16.379	error	TypeError: path.actions.getInfo is not a function
tr-064.0	2017-01-04 12:20:16.374	error	uncaught exception: path.actions.getInfo is not a function
tr-064.0	2017-01-04 12:20:11.300	info	starting. Version 0.1.16 in /volume1/iobroker/node_modules/iobroker.tr-064, node: v4.4.2

regards,
André

**Comment by buanet** [comment]
Looks like I'm not the only one...

http://forum.iobroker.net/viewtopic.php?f=22&t=4628

:)

**Comment by Apollon77** [comment]
And rollback via Admin is not possible because "news" in io-package-json are not provided
